#!/bin/sh
git_user_name=$1
git_password=$2
git_repository=${3:-hostanamelist2_1}
GITHUB=https://${git_user_name}:${git_password}@github.com/${git_user_name}/${git_repository}.git
WORKDIR=/var/tmp/fakedns2/hostnamelist
DELIMIT_STR="##fakedns entries start from here, dont remove."

if [ ! -d $WORKDIR ];then
        git clone $GITHUB $WORKDIR
else
        (cd $WORKDIR;git pull)
fi

MYHOST=`hostname`
MYIP=`ifconfig $NETWORKDEVICE | grep 'inet addr:' | sed -e 's/^.*inet addr://' |
 sed -e 's/[ ].*$//'`

echo $MYIP > $WORKDIR/$MYHOST

cd $WORKDIR
git add .
git commit -m "hostlist updated"
git push origin master

## split hosts file
while read aline;do
	if echo $aline | egrep -e '^'${DELIMIT_STR}
		break
	fi
	echo $aline
done < /etc/hosts > hosts.tmpl

echo ${DELIMIT_STR} >> hosts.tmpl

for fn in `ls $WORKDIR`;do
	entry="$fn      "`cat $fn`
	echo $entry
done | sort >> hosts.tmpl

# cp -f hosts.tmpl /etc/hosts

