#!/bin/sh
git_user_name=$1
git_password=$2
NETWORKDEVICE=${3:-eth0}
git_repository=${4:-hostnamelist2_1}
GITHUB=https://${git_user_name}:${git_password}@github.com/${git_user_name}/${git_repository}.git
WORKDIR=/var/tmp/fakedns2/hostnamelist
DELIMIT_STR="##fakedns entries start from here, dont remove."

if [ ! -d $WORKDIR ];then
        git clone $GITHUB $WORKDIR
else
        (cd $WORKDIR;git pull)
fi

MYHOST=`hostname`
MYIP=`ifconfig $NETWORKDEVICE | grep 'inet addr:' | sed -e 's/^.*inet addr://' | sed -e 's/[ ].*$//'`

echo $MYIP > $WORKDIR/$MYHOST

cd $WORKDIR
git add .
git commit -m "hostlist updated"
git push origin master

## split hosts file
while read aline;do
	if echo $aline | egrep -e '^'"${DELIMIT_STR}" > /dev/null 2>&1 ;then
		break
	fi
	echo $aline
done < /etc/hosts > /tmp/hosts.tmpl

echo ${DELIMIT_STR} >> /tmp/hosts.tmpl

for fn in `ls $WORKDIR`;do
	entry=`cat $fn`"          $fn"
	echo $entry
done | sort >> /tmp/hosts.tmpl

cp -f /tmp/hosts.tmpl /etc/hosts

